int tconst(void);
int bitNand(int x, int y);
int fastModulo(int x,int y);
int ezOverflow(int x,int y);
int findDifference(int x,int y);
int absVal(int x);
int secondLowBit(int x);
int byteSwap(int x, int n, int m);
int byteCheck(int x);
int fractions(int x);
int biggerOrEqual(int x, int y);
int hdOverflow(int x,int y);
int overflowCalc(int x, int y, int z);
int logicalShift(int x, int n);
int partialFill(int l, int h);
unsigned float_abs(unsigned uf);
unsigned float_cmp(unsigned uf1, unsigned uf2);
unsigned float_pow2(unsigned uf,int n);
unsigned float_i2f(int x);
int oddParity(int x);
int bitReverse(int x);
int mod7(int x);

int test_tconst(void);
int test_bitNand(int x, int y);
int test_fastModulo(int x,int y);
int test_ezOverflow(int x,int y);
int test_findDifference(int x,int y);
int test_absVal(int x);
int test_secondLowBit(int x);
int test_byteSwap(int x, int n, int m);
int test_byteCheck(int x);
int test_fractions(int x);
int test_biggerOrEqual(int x, int y);
int test_hdOverflow(int x,int y);
int test_overflowCalc(int x, int y, int z);
int test_logicalShift(int x, int n);
int test_partialFill(int l, int h);
unsigned test_float_abs(unsigned uf);
unsigned test_float_cmp(unsigned uf1, unsigned uf2);
unsigned test_float_pow2(unsigned uf,int n);
unsigned test_float_i2f(int x);
int test_oddParity(int x);
int test_bitReverse(int x);
int test_mod7(int x);
